export const ITD_SELECTOR_TYPE = 'box'
export const ITD_SELECTOR_RADIUS = '5'
export const ITD_SELECTOR_BG_ON = 'rgba(255,0,0,0.2)'
export const ITD_SELECTOR_BG_OFF = 'rgba(0,255,0,0)'
export const ITD_SELECTOR_BO_ON = '2px solid red'
export const ITD_SELECTOR_BO_OFF = 'none'
